name: build-and-publish

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build container image
        run: |
          docker build -t new-app:latest .

      - name: Simulate push
        run: echo "Image pushed to registry"
